In [2]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt 

%matplotlib inline 

In [ ]:
np.array([1,2,3,4])


In [8]:
a=np.array([1,2,3,4,5])
b=np.array([0.5,1,2.5,6])

In [10]:
a[0],a[1]
a[0:]

array([1, 2, 3, 4, 5])

In [11]:
b[[0,2,-1]]

array([0.5, 2.5, 6. ])

In [13]:
a.dtype

dtype('int64')

In [14]:
np.array([1,2,3,4,5],dtype=np.float32)

array([1., 2., 3., 4., 5.], dtype=float32)