# Numpy, Pandas

In [1]:
import numpy as np

In [2]:
a = np.array(1)
print(a, a.ndim)

1 0


In [3]:
b = np.array([1,2,3,4,5])
#print(b, b.ndim)
c = np.array([[1,2,3], [4,5,6]])

d = np.array([[[1,2,3], [4,5,6]], 
              [[7,8,9], [10,11,12]]])
print(d, d.ndim)
print(d[:, :, :2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] 3
[[[ 1  2]
  [ 4  5]]

 [[ 7  8]
  [10 11]]]


In [4]:
print(c)
print(c[0, 2])
print(c[0:2, 2])
print(c[:, 1])

[[1 2 3]
 [4 5 6]]
3
[3 6]
[2 5]


In [5]:
print(d)
print(d[0,0,0])


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
1


In [6]:
print(d[0,:,1:3])
print(d[1,:,1:3])
print(d[0,:,0:2])
print(d[:,:,1])


[[2 3]
 [5 6]]
[[ 8  9]
 [11 12]]
[[1 2]
 [4 5]]
[[ 2  5]
 [ 8 11]]


In [7]:
b = np.array([1,2,3,4,5,6])
print(b)
bcopy = b.copy()
bcopy[1] = 0
print(b)
print(bcopy)

[1 2 3 4 5 6]
[1 2 3 4 5 6]
[1 0 3 4 5 6]


In [8]:
bview = b.view()
bview[1] = 0
print(b)
print(bview)

[1 0 3 4 5 6]
[1 0 3 4 5 6]


In [9]:
print(c)
rows, cols = c.shape
print(rows, cols)
print(c.reshape(-1,6))


[[1 2 3]
 [4 5 6]]
2 3
[[1 2 3 4 5 6]]


In [10]:
print(d)
d.reshape(2,-1,2)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [11]:
b = np.array([3,2,16,4,9])
print(b)
for ele in b:
    print(ele)

[ 3  2 16  4  9]
3
2
16
4
9


In [12]:
print(c)
for oneDarr in c:
    for ele in oneDarr:
        print(ele)

[[1 2 3]
 [4 5 6]]
1
2
3
4
5
6


In [13]:
print(c)
for ele in np.nditer(c):
    print(ele)

[[1 2 3]
 [4 5 6]]
1
2
3
4
5
6


In [14]:
print(c)
for indx, ele in np.ndenumerate(c):
    print(indx, ele)

[[1 2 3]
 [4 5 6]]
(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6


In [15]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.concatenate((a,b))
print(c)

[1 2 3 4 5 6]


In [16]:
d = np.array([[1,2], [3,4]])
e = np.array([[5,6], [7,8]])
print(d)
print(e)
print(np.concatenate((d,e), axis=0))
print(np.concatenate((d,e), axis=1))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [17]:
print(a)
print(b)
print(np.stack((a,b), axis = 0))
print(np.stack((a,b), axis = 1))
print(np.hstack((a,b)))
print(np.vstack((a,b)))
print(np.dstack((a,b)))

[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[[1 4]
  [2 5]
  [3 6]]]


In [18]:
a = np.array([1,2,3,4,5,6])
np.array_split(a, 4)

[array([1, 2]), array([3, 4]), array([5]), array([6])]

In [19]:
print(a)
indx = np.where(a%2 == 0)
print(indx)
print(a[indx])

[1 2 3 4 5 6]
(array([1, 3, 5]),)
[2 4 6]


In [20]:
x = np.zeros((3,3))
print(x)
y = np.ones((3,3))
print(y)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [21]:
a = np.array([[1,2,3], [4, 5,6]])
b = np.array([[1,2], [3,4], [5,6]])
print(a@b)
print(np.dot(a,b))
print(b.T)
print(np.multiply(a, b.T))

[[22 28]
 [49 64]]
[[22 28]
 [49 64]]
[[1 3 5]
 [2 4 6]]
[[ 1  6 15]
 [ 8 20 36]]


In [22]:
x = np.array([[1,2], [3,7]])
xinv = np.linalg.inv(x)
print(x@xinv)
w,v = np.linalg.eig(x)
print(w)
print(v)

[[ 1.0000000e+00 -4.4408921e-16]
 [ 0.0000000e+00  1.0000000e+00]]
[0.12701665 7.87298335]
[[-0.91649636 -0.2794051 ]
 [ 0.40004303 -0.96017331]]


In [23]:
y = np.linspace(0,20, 9)
print(y)

[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20. ]


In [24]:
x = np.arange(0,20, 6)
print(x)

[ 0  6 12 18]


In [25]:
#pip install pandas 
import pandas as pd
data = {'Name':['Ram', 'Syam', 'Somu'], 
        'Branch': ['CSE', 'ECE', 'EEE']}
df = pd.DataFrame(data)
print(df)
print(df.Name)
print(df.Branch)
print(df['Name'])
print(df[['Name', 'Branch']])

   Name Branch
0   Ram    CSE
1  Syam    ECE
2  Somu    EEE
0     Ram
1    Syam
2    Somu
Name: Name, dtype: object
0    CSE
1    ECE
2    EEE
Name: Branch, dtype: object
0     Ram
1    Syam
2    Somu
Name: Name, dtype: object
   Name Branch
0   Ram    CSE
1  Syam    ECE
2  Somu    EEE


In [26]:
print(df)
print(df.loc[1])
print(df.loc[1].Branch)
print(df.loc[1, 'Branch'])

   Name Branch
0   Ram    CSE
1  Syam    ECE
2  Somu    EEE
Name      Syam
Branch     ECE
Name: 1, dtype: object
ECE
ECE


In [27]:
import pandas as pd
data = {'Name':['Ram', 'Syam', 'Somu'], 
        'Branch': ['CSE', 'ECE', 'EEE']}
df = pd.DataFrame(data, index = ['x', 'y', 'z'])
print(df)
print(df.loc['y', 'Branch'])

   Name Branch
x   Ram    CSE
y  Syam    ECE
z  Somu    EEE
ECE


In [28]:
a = [1,2,3]
ds = pd.Series(a)
print(ds)

0    1
1    2
2    3
dtype: int64


In [29]:
data = pd.read_csv('Sample2.csv')
#df = pd.DataFrame(data)
print(data)
print(data.head(3))
print(data.tail(3))
print(data.info())

   ID      NAME BRANCH  AGE
0   1   Sandhya    CSE   22
1   2  Narayana    ECE   21
2   3    Venkat    CSE   20
3   4     Durga    EEE   18
4   5   Saranya  CIVIL   19
5   6      Bala    CSE   22
   ID      NAME BRANCH  AGE
0   1   Sandhya    CSE   22
1   2  Narayana    ECE   21
2   3    Venkat    CSE   20
   ID     NAME BRANCH  AGE
3   4    Durga    EEE   18
4   5  Saranya  CIVIL   19
5   6     Bala    CSE   22
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   ID      6 non-null      int64 
 1   NAME    6 non-null      object
 2   BRANCH  6 non-null      object
 3   AGE     6 non-null      int64 
dtypes: int64(2), object(2)
memory usage: 320.0+ bytes
None


In [30]:
print(data)
print(data.ID)
print(data[['ID', 'BRANCH']])


   ID      NAME BRANCH  AGE
0   1   Sandhya    CSE   22
1   2  Narayana    ECE   21
2   3    Venkat    CSE   20
3   4     Durga    EEE   18
4   5   Saranya  CIVIL   19
5   6      Bala    CSE   22
0    1
1    2
2    3
3    4
4    5
5    6
Name: ID, dtype: int64
   ID BRANCH
0   1    CSE
1   2    ECE
2   3    CSE
3   4    EEE
4   5  CIVIL
5   6    CSE


In [31]:
print(data[['ID', 'BRANCH']][0::3])

   ID BRANCH
0   1    CSE
3   4    EEE


In [32]:
print(data)
print(data.loc[data.AGE<=20])

   ID      NAME BRANCH  AGE
0   1   Sandhya    CSE   22
1   2  Narayana    ECE   21
2   3    Venkat    CSE   20
3   4     Durga    EEE   18
4   5   Saranya  CIVIL   19
5   6      Bala    CSE   22
   ID     NAME BRANCH  AGE
2   3   Venkat    CSE   20
3   4    Durga    EEE   18
4   5  Saranya  CIVIL   19


In [33]:
print(data.sort_values('AGE'))
print(data.sort_values('AGE', ascending = False))


   ID      NAME BRANCH  AGE
3   4     Durga    EEE   18
4   5   Saranya  CIVIL   19
2   3    Venkat    CSE   20
1   2  Narayana    ECE   21
0   1   Sandhya    CSE   22
5   6      Bala    CSE   22
   ID      NAME BRANCH  AGE
0   1   Sandhya    CSE   22
5   6      Bala    CSE   22
1   2  Narayana    ECE   21
2   3    Venkat    CSE   20
4   5   Saranya  CIVIL   19
3   4     Durga    EEE   18


In [34]:
data2 = pd.read_csv('Sample3.csv')
print(data2)

   ID      NAME BRANCH  AGE
0   1   Sandhya    CSE   22
1   2  Narayana    ECE   21
2   3    Venkat    CSE   20
3   4     Durga    EEE   18
4   5   Saranya  CIVIL   19
5   6      Bala    CSE   22


In [35]:
data3 = pd.read_csv('students.csv')
print(data3)

     ID     NAME BRANCH  AGE  S1    S2  S3
0   101      ram    CSE   22  70  70.0  70
1   102     somu    ECE   21  67  69.0  70
2   103      ali    CSE   20  75  85.0  85
3   103    david    CSE   20  75  85.0  85
4   104     kamu    EEE   18  80   NaN  55
5   105      sri  CIVIL   19  65  67.0  89
6   105  Saranya  CIVIL   19  65  67.0  89
7   106     Bala    CSE   22  78  79.0  54
8   106    sanju    CSE   22  78  79.0  54
9   107     Sasi   MECH   21  80  80.0  85
10  106     Bala    CSE   22  78  79.0  54


In [36]:
data3.drop_duplicates(inplace = True)
print(data3)

    ID     NAME BRANCH  AGE  S1    S2  S3
0  101      ram    CSE   22  70  70.0  70
1  102     somu    ECE   21  67  69.0  70
2  103      ali    CSE   20  75  85.0  85
3  103    david    CSE   20  75  85.0  85
4  104     kamu    EEE   18  80   NaN  55
5  105      sri  CIVIL   19  65  67.0  89
6  105  Saranya  CIVIL   19  65  67.0  89
7  106     Bala    CSE   22  78  79.0  54
8  106    sanju    CSE   22  78  79.0  54
9  107     Sasi   MECH   21  80  80.0  85


In [37]:
data3.dropna(inplace = True)
print(data3)

    ID     NAME BRANCH  AGE  S1    S2  S3
0  101      ram    CSE   22  70  70.0  70
1  102     somu    ECE   21  67  69.0  70
2  103      ali    CSE   20  75  85.0  85
3  103    david    CSE   20  75  85.0  85
5  105      sri  CIVIL   19  65  67.0  89
6  105  Saranya  CIVIL   19  65  67.0  89
7  106     Bala    CSE   22  78  79.0  54
8  106    sanju    CSE   22  78  79.0  54
9  107     Sasi   MECH   21  80  80.0  85


In [38]:
data3 = pd.read_csv('students.csv')
print(data3)
data3.S2  = data3.S2.fillna(100)
print(data3)

     ID     NAME BRANCH  AGE  S1    S2  S3
0   101      ram    CSE   22  70  70.0  70
1   102     somu    ECE   21  67  69.0  70
2   103      ali    CSE   20  75  85.0  85
3   103    david    CSE   20  75  85.0  85
4   104     kamu    EEE   18  80   NaN  55
5   105      sri  CIVIL   19  65  67.0  89
6   105  Saranya  CIVIL   19  65  67.0  89
7   106     Bala    CSE   22  78  79.0  54
8   106    sanju    CSE   22  78  79.0  54
9   107     Sasi   MECH   21  80  80.0  85
10  106     Bala    CSE   22  78  79.0  54
     ID     NAME BRANCH  AGE  S1     S2  S3
0   101      ram    CSE   22  70   70.0  70
1   102     somu    ECE   21  67   69.0  70
2   103      ali    CSE   20  75   85.0  85
3   103    david    CSE   20  75   85.0  85
4   104     kamu    EEE   18  80  100.0  55
5   105      sri  CIVIL   19  65   67.0  89
6   105  Saranya  CIVIL   19  65   67.0  89
7   106     Bala    CSE   22  78   79.0  54
8   106    sanju    CSE   22  78   79.0  54
9   107     Sasi   MECH   21  80   80.0  85


In [39]:
data3 = pd.read_csv('students.csv')
print(data3)
data3.S2  = data3.S2.fillna(data3.S2.mean())
print(data3)

     ID     NAME BRANCH  AGE  S1    S2  S3
0   101      ram    CSE   22  70  70.0  70
1   102     somu    ECE   21  67  69.0  70
2   103      ali    CSE   20  75  85.0  85
3   103    david    CSE   20  75  85.0  85
4   104     kamu    EEE   18  80   NaN  55
5   105      sri  CIVIL   19  65  67.0  89
6   105  Saranya  CIVIL   19  65  67.0  89
7   106     Bala    CSE   22  78  79.0  54
8   106    sanju    CSE   22  78  79.0  54
9   107     Sasi   MECH   21  80  80.0  85
10  106     Bala    CSE   22  78  79.0  54
     ID     NAME BRANCH  AGE  S1    S2  S3
0   101      ram    CSE   22  70  70.0  70
1   102     somu    ECE   21  67  69.0  70
2   103      ali    CSE   20  75  85.0  85
3   103    david    CSE   20  75  85.0  85
4   104     kamu    EEE   18  80  76.0  55
5   105      sri  CIVIL   19  65  67.0  89
6   105  Saranya  CIVIL   19  65  67.0  89
7   106     Bala    CSE   22  78  79.0  54
8   106    sanju    CSE   22  78  79.0  54
9   107     Sasi   MECH   21  80  80.0  85
10  106    